### ISSUE TITLE
mem is one word too short

### ISSUE THREAD

**Issue by tanriol** [nomemory/lc3-vm#4]
The VM memory is defined as

```c
uint16_t mem[UINT16_MAX] = {0};
```

which means that `mem[UINT16_MAX]` would be an out of bounds read/write as the memory is 65535 words instead of 65536.

**Comment by nomemory** [comment]
You are right, when i find a little time i will modify the article and the source code.
Thank you for spotting this!

**Comment by nomemory** [comment]
Did the changes. Thank you for raising this.
